contracts_folder: tests/data/contracts/ethereum/local

ethereum:
  local:
    default_provider: hardhat

polygon:
  local:
    default_provider: hardhat
  amoy:
    default_provider: alchemy

hardhat:
  request_timeout: 29
  fork_request_timeout: 360
  bin_path: "./node_modules/.bin/hardhat"

  fork:
    ethereum:
      mainnet:
        upstream_provider: alchemy
        block_number: 17040366
        host: 127.0.0.1:7110
      sepolia:
        upstream_provider: alchemy
        block_number: 3091950
        host: 127.0.0.1:7112
      holesky:
        upstream_provider: alchemy
        block_number: 100
        host: 127.0.0.1:7116

    polygon:
      amoy:
        host: 127.0.0.1:7113

test:
  # `false` because running pytest within pytest.
  disconnect_providers_after: false

  gas:
    exclude:
      - method_name: setAdd*
