contracts_folder: tests/data/contracts/ethereum/local

ethereum:
  local:
    default_provider: hardhat
  mainnet:
    default_provider: node

polygon:
  local:
    default_provider: hardhat
  amoy:
    default_provider: node

node:
  ethereum:
    mainnet:
      uri: https://ethereum.publicnode.com
    sepolia:
      uri: https://ethereum-sepolia-rpc.publicnode.com
    holesky:
      uri: https://ethereum-holesky-rpc.publicnode.com
  polygon:
    amoy:
      uri: https://polygon-amoy-bor-rpc.publicnode.com

hardhat:
  request_timeout: 29
  fork_request_timeout: 360
  bin_path: "./node_modules/.bin/hardhat"

  fork:
    ethereum:
      mainnet:
        upstream_provider: node
        block_number: 17040366
        host: 127.0.0.1:7110
      sepolia:
        upstream_provider: node
        block_number: 3091950
        host: 127.0.0.1:7112
      holesky:
        upstream_provider: node
        block_number: 100
        host: 127.0.0.1:7116

    polygon:
      amoy:
        upstream_provider: node
        host: 127.0.0.1:7113

test:
  # `false` because running pytest within pytest.
  disconnect_providers_after: false

  gas:
    exclude:
      - method_name: setAdd*

  balance: 100_000 ETH
