on: ["push", "pull_request"]

name: Test

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
    linting:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v6

        - name: Install uv
          uses: astral-sh/setup-uv@v7
          with:
              python-version: "3.10"

        - name: Install Dependencies
          run: uv sync --group lint

        - name: Run Ruff Lint
          run: uv run ruff check .

        - name: Run Ruff Format
          run: uv run ruff format --check .

        - name: Run mdformat
          run: uv run mdformat --check README.md CONTRIBUTING.md docs

    type-check:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v6

        - name: Install uv
          uses: astral-sh/setup-uv@v7
          with:
              python-version: "3.10"

        - name: Install Dependencies
          run: uv sync --group lint --group test

        - name: Run MyPy
          run: uv run mypy .

    functional:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest]
                python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]

        steps:
        - uses: actions/checkout@v6

        - name: Install uv
          uses: astral-sh/setup-uv@v7
          with:
              python-version: ${{ matrix.python-version }}

        - name: Install Dependencies
          run: uv sync --group test

        - name: Setup Node
          uses: actions/setup-node@v4
          with:
              node-version: '18'

        - name: Install Node Dependencies
          run: npm install

        - name: Run Async Tests
          run: uv run ape test -m "not fork and not manual and not fuzzing"

        - name: Run Sync Tests
          if: github.event.pull_request.head.repo.full_name == github.repository
          run: uv run ape test -m fork
          env:
            WEB3_ALCHEMY_PROJECT_ID: ${{ secrets.WEB3_ALCHEMY_PROJECT_ID }}
